<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Akhil" tests="5" failures="1" timestamp="24 Nov 2015 07:13:21 GMT" time="457.579" errors="0">
  <testcase name="TestCase1" time="127.56" classname="WalmartLabsHwTest">
    <failure type="java.lang.AssertionError" message="expected [1] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [5]
	at WalmartLabsHwTest.TestCase1(WalmartLabsHwTest.java:85)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TestCase1 -->
  <testcase name="TestCase2" time="36.834" classname="WalmartLabsHwTest"/>
  <testcase name="TestCase3" time="188.683" classname="WalmartLabsHwTest"/>
  <testcase name="TestCase4" time="44.416" classname="WalmartLabsHwTest"/>
  <testcase name="TestCase5" time="40.171" classname="WalmartLabsHwTest"/>
</testsuite>
